# Generated by Django 5.0.1 on 2024-02-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HousingPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('furnished', models.JSONField(blank=True, null=True)),
                ('facilities', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
