# Generated by Django 5.0.1 on 2024-02-09 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HousingPost',
        ),
    ]
