# Generated by Django 5.0.1 on 2024-03-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="housingpost",
            name="address",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
