# Generated by Django 5.0.1 on 2024-03-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_rename_accessibility_housingpost_accessibilities"),
    ]

    operations = [
        migrations.AddField(
            model_name="housingpost",
            name="furnished_type",
            field=models.CharField(
                choices=[
                    ("fully furnished", "Fully Furnished"),
                    ("partially furnished", "Partially Furnished"),
                ],
                default=None,
                max_length=20,
            ),
        ),
    ]
