# Generated by Django 5.0.1 on 2024-02-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_housingpost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housingpost',
            name='title',
            field=models.CharField(max_length=10),
        ),
    ]
