# Generated by Django 5.0.1 on 2024-03-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_housingpost_furnished_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="housingpost",
            name="utilities_included",
            field=models.BooleanField(default=False),
        ),
    ]
