# Generated by Django 5.0.1 on 2024-02-09 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_housingpost_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HousingPost',
        ),
    ]
