# Generated by Django 5.0.1 on 2024-03-30 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0006_housingpost_utilities_included"),
    ]

    operations = [
        migrations.AddField(
            model_name="housingpost",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
