# Generated by Django 5.0.1 on 2024-04-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0007_housingpost_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="housingpost",
            name="accessibilities",
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name="housingpost",
            name="address",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="housingpost",
            name="description",
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name="housingpost",
            name="facilities",
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name="housingpost",
            name="furnished",
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name="housingpost",
            name="furnished_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fully furnished", "Fully Furnished"),
                    ("partially furnished", "Partially Furnished"),
                ],
                default=None,
                max_length=20,
            ),
        ),
    ]
