# Generated by Django 5.0.1 on 2024-02-09 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housingpost',
            name='description',
        ),
        migrations.RemoveField(
            model_name='housingpost',
            name='facilities',
        ),
    ]
