# Generated by Django 5.0.1 on 2024-02-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_remove_housingpost_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingpost',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='housingpost',
            name='facilities',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='housingpost',
            name='furnished',
            field=models.TextField(default=None),
        ),
    ]
