# Generated by Django 5.0.1 on 2024-02-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_housingpost_description_housingpost_facilities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housingpost',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
