# Generated by Django 5.2.14 on 2026-05-05 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0010_temporal_tables"),
        ("post", "0011_fulltext_search_v2"),
    ]

    operations = []
