# Generated by Django 5.0.1 on 2024-02-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0012_housingpost_gender_housingpost_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="housingpost",
            name="number_of_people",
            field=models.IntegerField(default=1),
        ),
    ]
