# Generated by Django 5.0.1 on 2024-02-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0013_housingpost_number_of_people"),
    ]

    operations = [
        migrations.AlterField(
            model_name="housingpost",
            name="images",
            field=models.ImageField(upload_to="housing_post_images/"),
        ),
    ]
