# Generated by Django 5.0.1 on 2024-02-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0014_alter_housingpost_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="housing_post_images")),
            ],
        ),
        migrations.RemoveField(
            model_name="housingpost",
            name="images",
        ),
        migrations.AddField(
            model_name="housingpost",
            name="images",
            field=models.ManyToManyField(to="post.image"),
        ),
    ]
