# Generated by Django 5.0.1 on 2024-02-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0015_image_remove_housingpost_images_housingpost_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="housingpost",
            name="deposit",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="housingpost",
            name="monthly_payment",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
