# Generated by Django 5.0.1 on 2024-02-13 10:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0016_housingpost_deposit_housingpost_monthly_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="housingpost",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
