# Generated by Django 5.0.1 on 2024-02-13 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0018_housingpost_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="housingpost",
            name="images",
        ),
        migrations.DeleteModel(
            name="Image",
        ),
    ]
