# Generated by Django 5.0.1 on 2024-02-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0020_remove_housingpost_timestamp_housingpost_date_posted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="housingpost",
            name="description",
            field=models.TextField(default=None),
        ),
    ]
